[variables]
NPM_CONFIG_NODE_GYP = "/usr/bin/node-gyp"

[phases.setup]
nixPkgs = ["bun", "nodejs", "python3", "gcc", "gnumake", "nodePackages.node-gyp"]

[phases.install]
cmds = [
  "which node-gyp",
  "bun install --frozen-lockfile"
]

[start]
cmd = "bun run dev"